import type { Metadata } from "next";
import { Navbar } from "./components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <Navbar />
        <div className="mx-auto max-w-screen-xl px-4 h-content pb-4">{children}</div>
      </body>
    </html>
  );
}
